@echo off
echo Setting up virtual environment for ml3...
cd c:\Users\praya\OneDrive\Desktop\finalapp_D\ml3
python -m venv venv
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Setup complete. Running model training...
python train_model.py
echo Testing inference...
python predict.py
pause
